### ISSUE TITLE
Propose updating to v4.3.2

### ISSUE THREAD

**Issue by lindy65** [ist-dsi/mattermost-cookbook#10]
Hi @magicknot,

Just want to inform you that v4.3.2 has been released.

You can find the Changelog [here](https://docs.mattermost.com/administration/changelog.html#release-v4-3-2) and the download links [here](https://pre-release.mattermost.com/core/pl/x6x1huk5eibh9m4ggn4xjtjjnh).

Thanks for maintaining Mattermost Cookbook!

**Comment by magicknot** [comment]
It's done and release to supermarket :)
