### ISSUE TITLE
Propose updating to Mattermost 4.4.1

### ISSUE THREAD

**Issue by lindy65** [ist-dsi/mattermost-cookbook#11]
Hi @magicknot,

Mattermost v4.4.1 is officially out!

You can [find download links with hash numbers here](https://pre-release.mattermost.com/core/pl/ph9peatubtne7pszys4utsyo3c).  Changelog with notes on patch releases is available [here](https://docs.mattermost.com/administration/changelog.html#release-v4-4-1).

If you do update, please consider tweeting about it, which we can then re-tweet for greater reach. 

Thanks!

**Comment by magicknot** [comment]
Hey @lindy65! Thanks once again for the reminder. I've just submitted the new version to [Chef Supermarket](https://supermarket.chef.io/cookbooks/mattermost-cookbook)!
