### ISSUE TITLE
Help update to Mattermost v4.2?

### ISSUE THREAD

**Issue by lindy65** [ist-dsi/mattermost-cookbook#3]
Hi @magicknot,

Mattermost v4.2 is officially out.  Please help update to the latest version?

You can [view the full changelog for Mattermost 4.2 here](https://docs.mattermost.com/administration/changelog.html#release-v4-2-0) and [find download links with hash numbers here](https://pre-release.mattermost.com/core/pl/rfmj6xak9irifx5598j3jtgadc).

Thanks for maintaining the Mattermost Cookbook!

**Comment by magicknot** [comment]
Hey @lindy65, I'm currently out of town so I can't deploy the release for Mattermost 4.2 yet. If everything goes well, I'll release it next Friday.
