### ISSUE TITLE
Update Mattermost to v4.3.1

### ISSUE THREAD

**Issue by lindy65** [ist-dsi/mattermost-cookbook#8]
Hi @magicknot,

Mattermost v4.3.1 dot release is officially out.  

You can [find download links with hash numbers here](https://pre-release.mattermost.com/core/pl/1m4s4q1q97fezgzuuod4ag8tah).  Changelog with notes on patch releases will be available [here](https://docs.mattermost.com/administration/changelog.html#mattermost-changelog) later today.

**Comment by magicknot** [comment]
Hey @lindy65 I can only seem to find v4.3.1-RC1. Is that the final release?

**Comment by lindy65** [comment]
Ah, so sorry! That is the RC1 link. My mistake... I'll let you know once final is cut...

**Comment by lindy65** [comment]
Hi @magicknot,

Once again, apologies for the RC link.  Here is the link to the final v4.3.1 build: https://pre-release.mattermost.com/core/pl/jtshyqakrbga8cqiucx6pci47c

**Comment by magicknot** [comment]
Thank you @lindy65.

**Comment by lindy65** [comment]
FYI, link to the [Changelog](https://docs.mattermost.com/administration/changelog.html#release-v4-3-1) in case you need it :)

**Comment by magicknot** [comment]
Hey @lindy65, I missed the changelog. Thank you. I have released a new version of the cookbook.
